{
 "title": "Dr.Electron dRNG metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "grpc_method", "query": "label_values(grpc_method)" },
   {
    "name": "instance",
    "query": "label_values(beacon_discrepancy_latency,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows the time elapsed since the start of the node.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"drng_metrics\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "grafana-worldmap-panel",
   "description": "Shows node status and location",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "valueName": "total",
   "targets": [
    { "expr": "drng_status", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "beacon latency",
   "type": "graph",
   "description": "Discrepancy between beacon creation time and calculated round time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "beacon_discrepancy_latency{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client latency",
   "type": "graph",
   "description": "Duration between time round received and time round expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_watch_latency{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Group connections",
   "type": "graph",
   "description": "Number of peers with current GrpcClient connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "group_connections{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC RX",
   "type": "graph",
   "description": "Total number of RPC stream messages received on the server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_msg_received_total{grpc_method=~\"$grpc_method\", instance=~\"$instance\"}",
     "legendFormat": "{{grpc_method}}_{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC TX",
   "type": "graph",
   "description": "Total number of RPC stream messages sent on the server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_msg_sent_total{grpc_method=~\"$grpc_method\", instance=~\"$instance\"}",
     "legendFormat": "{{grpc_method}}_{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC started",
   "type": "graph",
   "description": "Total number of RPCs started on the server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_started_total{grpc_method=~\"$grpc_method\", instance=~\"$instance\"}",
     "legendFormat": "{{grpc_method}}_{{instance}}"
    }
   ]
  }
 ]
}